config/routes.rb
Rails.application.routes.draw do
  	get 'users/filter_by_email' => 'users#filter_by_email'
	get 'users/index' => 'users#index'
  
	post 'likes/toggle_comment_like/' => 'likes#toggle_comment_like'
	post 'likes/toggle_post_like/' => 'likes#toggle_post_like'

  get 'comments/create'

  get 'comments/destroy'
  
  devise_for :users
  get 'users/:id' => 'users#show'

  resources :posts, only: [:index, :create, :destroy]
  resources :comments, only: [:create, :destroy]

  root "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  has_many :likes, as: :likeable

  	def user_can_like(user)
		return self.likes.find_by(user: user).blank?
	end

	def current_like_status(user)
		if user_can_like(user)
			return 'Like'
		else
			return 'Unlike'
		end
	end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :user, presence: true

	belongs_to :user
	has_many :comments, dependent: :destroy

	has_many :likes, as: :likeable


	def user_can_like(user)
		return self.likes.find_by(user: user).blank?
	end

	def current_like_status(user)
		if user_can_like(user)
			return 'Like'
		else
			return 'Unlike'
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :profile_picture, default_url: "/system/images/:style/missing.png"
  validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\z/

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes


  has_many :friendships
  has_many :friends, through: :friendships


  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'

  has_many :inverse_friends, through: :inverse_friendships, source: :user


  def get_all_friends
  	friend_ids = self.friends.all.pluck(:id)

  	inverse_friend_ids = self.inverse_friends.all.pluck(:id)

  	all_friends = friend_ids + inverse_friend_ids

  	return User.where('id in (?)', all_friends)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]
  before_action :authorize_user, only: [:destroy]


  def create

  	@comment = Comment.new(comment_params)
  	@comment.user = current_user
  	@comment.save
    @post = @comment.post
    UserMailer.new_comment_email(@comment).deliver_now

  end

  def destroy
  	@comment_id = @comment.id

  	@comment.destroy
  end

  private

  def comment_params
  	params.require(:comment).permit(:post_id, :content)
  end

  def set_comment
  	@comment = Comment.find(params[:id])
  end

  def authorize_user
  	if @comment.user != current_user
  		return redirect_to root_path
  	end
  	return true

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!


	def toggle_post_like
		@post = Post.find(params[:post_id])
		@new_like_status = 'Unlike'

		if @post.user_can_like(current_user)
			Like.create(
				user: current_user,
				likeable: @post
				)
		else
			Like.find_by(
				user: current_user,
				likeable: @post
				).destroy
			@new_like_status = 'Like'

		end 

	end


	def toggle_comment_like
		@comment = Post.find(params[:comment_id])
		@new_like_status = 'Unlike'

		if @comment.user_can_like(current_user)
			Like.create(
				user: current_user,
				likeable: @comment
				)
		else
			Like.find_by(
				user: current_user,
				likeable: @comment
				).destroy
			@new_like_status = 'Like'

		end 
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_post, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  def index
    query = params[:q]
  	@post = Post.new
  	@comment = Comment.new
    if (query.blank?)
      @posts = Post.all
    else
  	 @posts = Post.where('content like ?', ('%' + query + '%')).reverse()
    end
    return @posts
  end

  def create
  	@post = Post.new(post_params)
  	@post.user = current_user
  	@post.save
  	@comment = Comment.new
  end

  def destroy
    @post_id = @post.id
  	@post.destroy
  	
  end

  private

  def post_params
  	params.require(:post).permit(:content)
  end

  def set_post
  	@post = Post.find(params[:id])
  end

  def authorize_user
  	if @post.user != current_user
  		return redirect_to root_path
  	end
  	return true

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
		@user = User.find(params[:id])
	end

    def index
		@user=User.all
    end

    def add_friend
    end

	def filter_by_email
		users = User.where('email like ?', ('%' + params[:term] + '%'))

		users_list = []
		users.each do |u|
			user = Hash.new
			user[:id] = u.id 
			user[:value] = u.email
			user[:label] = u.email
			users_list << user
		end

		return render json: users_list
	end

	def update
		user = User.find(params[:id])
		user.update(
			email: params[:user][:email],
			profile_picture: params[:user][:profile_picture]
			)
		byebug
		return redirect_to user_show_path(user.id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= com.id %>">
	<div>
		<p>
		<%= com.content %>
		</p>
		<p class="comment-likes">
				<span class="user-like-status">
					<% if user_signed_in? %>
						<%= link_to "#{com.current_like_status(current_user)}", likes_toggle_comment_like_path(comment_id: com.id), remote: true, method: :post %>
					<% end %>
				</span>
				<span class="user-like-count">
					<%= com.likes.length %> Likes
				</span>
			</p>
		<p class="author-details"><%= com.user.email%> at <%= com.created_at %>
		</p>
	</div>
	
	<p class="comment-destroy-link">
		<% if user_signed_in? && com.user == current_user %>
		<%= link_to "X", comment_path(com.id), remote: true, method: :delete %>
		<% end %>
	</p>
</li>

app/views/comments/create.js.erb
$('#comments-list-<%= @post.id %>').append('<%= escape_javascript render "comment", com: @comment%>');
$('#comments-container-<%= @post.id %> textarea').val('');
noty({
	text: 'Commented successfully',
	type: 'information',
	timeout: 2000
});

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();
noty({
	text: 'Comment destroyed!!',
	type: 'information',
	timeout: 2000
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Allsocial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'components/test', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'components/test', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-noty/2.4.1/packaged/jquery.noty.packaged.min.js"></script>
  <script type="text/javascript" src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
  <meta name="viewport" content="initial-scale=1.0, width=device-width">
  <script type="text/javascript" src=""></script>
  <%= csrf_meta_tags %>
</head>
<body>

	<header id="body-header">
		<div id="page-logo">
			<%= link_to "/" do%>
				<%= image_tag("reddit-logo.png") %>
			<% end %>
		</div>

		<div id="auth-links">
			<ul>
			    <p>
						<%= link_to "Users", users_index_path %>
				</p>
				<% if !user_signed_in? %>
					<% if !current_page?(new_user_session_path) %>
					<li>
						<p>
							<%= link_to "Sign In", new_user_session_path %>
						</p>
					</li>
					<% end %>
					<% if !current_page?(new_user_registration_path) %>
					<li>
						<p>
							<%= link_to "Sign Up", new_user_registration_path %>
						</p>
					</li>
					<% end %>
				<% else %>
				<li>
					<i class="fa fa-user-circle-o "></i>
					<p><%= current_user.email %></p>
				</li>
				<li>
					<p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
				</li>
				<% end %>
				
			</ul>
		</div>
	</header>

<%= yield %>

</body>
</html>

app/views/likes/toggle_comment_like.js.erb
$('#comment-<%= @comment.id %> .comment-likes .user-like-status a').html("<%= @new_like_status %>");
$('#comment-<%= @comment.id %> .comment-likes .user-like-count').html("<%= @comment.likes.length %> Likes");

app/views/likes/toggle_post_like.js.erb
$('#post-<%= @post.id %> .post-likes .user-like-status a').html("<%= @new_like_status %>");
$('#post-<%= @post.id %> .post-likes .user-like-count').html("<%= @post.likes.length %> Likes");

app/views/posts/_post.html.erb
<li id="post-<%= p.id %>" class="post">
	<div class="post-content">
		<div class="text">
			<p >
				<%= p.content %>
			</p>
			<p class="post-likes">
				<span class="user-like-status">
					<% if user_signed_in? %>
						<%= link_to "#{p.current_like_status(current_user)}", likes_toggle_post_like_path(post_id: p.id), remote: true, method: :post %>
					<% end %>
				</span>
				<span class="user-like-count">
					<%= p.likes.length %> Likes
				</span>
			</p>
			<p class="author-details">
				<%= p.user.email%> at <%= p.created_at %>
			</p>
		</div>
		
		<p class="post-destroy-link">
			<% if user_signed_in? && p.user == current_user %>
			<%= link_to "X", post_path(p.id), remote: true, method: :delete %>
			<% end %>
		</p>
	</div>
	<div class="post-comments-container">
		<% if user_signed_in? %>
			<%= form_for @comment, remote: true do |f| %>
			    <i class="fa fa-comment-o"></i>
				<%= f.hidden_field :post_id, value: p.id %>
				<%= f.text_area :content, placeholder: "Add Comment" %>
				<%= f.submit %>
			<% end %>
		<% end %>
		<ul id="comments-list-<%= p.id %>" class="comments-list">
			<% p.comments.each do |com| %>
				<%= render 'comments/comment', com: com %>
			<% end %>
		</ul>
	</div>
</li>

app/views/posts/create.html.erb
something
<%= flash[:notice] %>

app/views/posts/create.js.erb
$('#posts-list').prepend("<%= escape_javascript  render 'post', p: @post %>");
noty({
	text: 'New Post Created',
	type: 'success',
	timeout: 2000
});
// if liked
// $('#post-like-<%= @post.id %> user-action').html('Unlike');
// else
// $('#post-like-<%= @post.id %> user-action').html('Like')
// end


// $('#post-like-<%= @post.id %> likes-count').html(<%= @post.likes.length %>)

// <div id="post-like-10" class="post-like">
// 	<span class="user-action"><link_to post-id></span>
// 	<span class="likes-count"></span>
// </div>

app/views/posts/destroy.js.erb
$('#post-<%= @post_id %>').remove();

app/views/posts/index.html.erb
<main>


	<div id="page-container">
		<div id="posts-container">
			<% if user_signed_in? %>
			<div id="new-post-form-container">
				<%= form_for @post, remote: true do |f| %>
					<%= f.label :content, "Add Post" %>
					<%= f.text_area :content, placeholder: "Type Here" %>
					<%= f.submit %>
				<% end %>
			</div>
			<% end %>

			<div id="posts-list-container">
				<ul id="posts-list">
					<% @posts.each do |post| %>
						<%= render 'post', p: post %>
					<% end %>
				</ul>
			</div>
		</div>
		<div id="friends-container">
			<h5>Friends</h5>
			<div id="user-search-container">
				<input id="user-search">
			</div>
		</div>
	</div>

</main>

app/views/users/index.html.erb
<% @user.each do |user|%>
  <% if !current_user %>
      <p>
        <i class="fa fa-user-circle-o "></i>
        <%= user.email%>
        <%= link_to "Add Friend"%>
      </p>

  <% else %>      
	<% if user.email !=current_user.email%>
		<p>
      <i class="fa fa-user-circle-o "></i>
			<%= user.email%>
			<%= link_to "Add Friend" %>	
		</p>
	<% end %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if current_user == @user %>
	<img id="my-profile-pic" src="<%= @user.profile_picture.url %>">
<!-- display profile edit form -->
	<%= form_for @user, html: { multipart: true } do |f|  %>

	<div class="field">
    <%= f.label :profile_picture %><br />
    <%= f.file_field :profile_picture%>
  	</div>


	<div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  	</div>

  	<%= f.submit %>

	<% end %>


<% else %>
<h4><%= @user.email %> Profile Page </h4>
<% end %>


<script type="text/javascript">

	
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
        	console.log('onload', e);
            $('#my-profile-pic').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}


$("#user_profile_picture").change(function(){
	console.log('change', event);
    readURL(this);
});

</script>